---
title: "SARforecastDLM"
subtitle: "Code to generate base data file"
output: html_document
date: "2025-01-13"
---

Objective: To generate the base data files for the SARforecastDLM package which include: 

- `base_plot_data.rda`: includes forecast results with all years for each sar.method and index -- used in mod_mainpage.R

# Load Libraries
```{r load_libraries}
library(tidyverse)
library(janitor)
library(MARSS)
library(broom)
library(here)
```
# Model Function
```{r fct_MARSS_model}
# Define the function
run_model_and_forecast <- function(data, inputQ, inputB, inputR, inputU) {
  
  train.data<- data %>% 
    filter(!is.na(logit.s))
  
  test.data <- data %>%
    dplyr::filter(is.na(logit.s))
  
  
  ## get time indices
  years <- train.data$year
  ## number of years of data
  TT <- length(years)
  ## get response variable: logit(survival)
  dat <- matrix(train.data$logit.s, nrow = 1)

  ## get predictor variable
  index <- train.data$value

  ## ## ## z-score the upwelling index
  index_z <- matrix((index - mean(index)) / sqrt(var(index)), nrow = 1)
  
  ## z-score normalize the test data using the training data's mean and variance
  index_z_test <- (test.data$value - mean(index)) / sqrt(var(index))


  ## number of regr params (slope + intercept) = 2
  m <- dim(index_z)[1] + 1

  ### build DLM
  
  B <- if (is.character(inputB) && inputB == "diag") diag(m) else inputB
  U <- if (is.character(inputU) && inputU == "0") matrix(0, nrow = m, ncol = 1) else if (inputU == "u") matrix("u", nrow = m, ncol = 1) else inputU
  Q <- if (is.character(inputQ) && inputQ == "diagonal and unequal") "diagonal and unequal" else inputQ
  R <- if (is.character(inputR) && inputR == "r") matrix("r") else matrix(as.numeric(inputR))
  
  print(paste("B:", B, "U:", U, "Q:", Q, "R:", R))
                
  Z <- array(NA, c(1, m, TT))  
  Z[1,1,] <- rep(1, TT)        
  Z[1,2,] <- index_z             
  A <- matrix(0)               

  ## list of initial values
  inits_list <- list(x0 = matrix(c(0, 0), nrow = m))

  ## list of model matrices & vectors
  mod_list <- list(B = B, U = U, Q = Q, Z = Z, A = A, R = R)


  ### fit DLM
  print(paste("Running model for:", unique(data$index), unique(data$sar.method), unique(data$reach)))
  dlm<- MARSS::MARSS(dat, inits = inits_list, model = mod_list)
    convergence_status <- ifelse(dlm$convergence == 0, "Success", "Warning")
  # autoplot(dlm, silent = TRUE, plot.type = c("fitted.ytT","fitted.ytt1", "xtT", "xtt1"))

  
  ## forecast
  forecast_ytt1<-MARSS::forecast(dlm, h= 1, newdata = list(z = index_z_test), type = "ytt1", interval = "confidence", fun.kf = "MARSSkfss") #removed adding last year data point to return NA for observed in pred output; y = train.data[nrow(train.data),2]

  
    # Determine the year vector based on the condition
  if (unique(data$sar.method) == "DART" && unique(data$reach) == "BON-BOA") {
    year_vector <- c(2000:2004, 2006:2023)
  } else {
    year_vector <- min(years):(max(years) + 1)
  }
  
  # map_sar_names<- c("Scheuerell and Williams (2005)" = "sw", "DART" = "dart", "CJS" = "cjs")
  # map_index_names<- c("CUI" = "cui", "CUTI" = "cuti", "ICPB" = "icpb", "NCBI" = "ncbi")
  # map_reach_names<- c("LGR_LGA" = "lgrlga", "BON_BOA" = "bonboa")
  

  forecast_df <- forecast_ytt1$pred %>% 
                    mutate(across(c(3:4, 6:9),~plogis(.x)*100)) %>% 
                    janitor::clean_names() %>% 
                    mutate(year = year_vector,
                          index = unique(data$index),
                          sar.method = unique(data$sar.method),
                          reach = unique(data$reach),
                          dataset = "base_forecast",
                          rear_type = "Natural-origin",
                          pass_type = "All", 
                          convergence = convergence_status) %>% 
                    inner_join(select(data, value, year), by = "year") %>% ##join index value
                    select(year, value, y, estimate, lo_95, hi_95,sar.method,index, reach, rear_type, pass_type, dataset, convergence)
  
  return(forecast_df)
}
```


```{r fct_MARSS_model_example, eval = FALSE}
params<-paramlist %>% filter(sar.method == "DART", index == "CUI", reach == "BON-BOA") 

# #example
mod<-run_model_and_forecast(
  data = sar_raw_data %>% filter(sar.method == "DART", index == "CUI", reach == "BON-BOA"),
  inputQ = params$Qinput,   
  inputB = params$Binput, 
  inputR = params$Rinput,
  inputU = params$Uinput  
)

paramlist <-paramlist %>% 
   mutate(
    Uinput = ifelse(index == "CUTI" & sar.method == "CJS" & reach == "LGR_LGA", "u", Uinput)
    # Rinput = ifelse(index == "CUI" & sar.method == "DART" & reach == "BON_BOA", "0.1", Rinput)
  )

paramlist<-DLM_parameter_list_param
usethis::use_data(paramlist, overwrite = TRUE)


```


# Run Function 
```{r run_model_and_forecast_loop_lookup}
load(here::here("data", "sar_raw_data.rda"))
load(here::here("data", "paramlist.rda"))


# Get the unique combinations of index and sar.method
combinations <- unique(sar_raw_data[, c("index", "sar.method", "reach")]) %>% drop_na()

forecast_output <- list()

for(i in seq_len(nrow(combinations))) {
  # Subset the data for the current combination
  data_subset <- sar_raw_data %>%
    filter(
        index == !!combinations$index[i],
        sar.method == !!combinations$sar.method[i],
        reach == !!combinations$reach[i]
           )
  
  # Get the parameter values for the current combination
  params <- paramlist %>%
    filter(
        index == !!combinations$index[i],
        sar.method == !!combinations$sar.method[i],
        reach == !!combinations$reach[i]
           ) %>% 
  mutate(across(everything(), as.character))

  
  # Run the model and get the forecast
  forecast <- run_model_and_forecast(
    data = data_subset, 
    inputQ = params$Qinput, 
    inputB = params$Binput, 
    inputR = params$Rinput, 
    inputU = params$Uinput
  )
  
  map_sar_names<- c("Scheuerell and Williams (2005)" = "sw", "DART" = "dart", "CJS" = "cjs")
  map_index_names<- c("CUI" = "cui", "CUTI" = "cuti", "ICPB" = "icpb", "NCBI" = "ncbi")
  map_reach_names<- c("LGR-LGA" = "lgrlga", "BON-BOA" = "bonboa", "Snake River Upper-Upper" = "uppupp")
  
  # Create the name for the sublist
  combination_name <- paste(map_sar_names[combinations$sar.method[i]], map_index_names[combinations$index[i]], map_reach_names[combinations$reach[i]], sep = "_")
  
  # Store the forecast in the list with the created name
  forecast_output[[combination_name]] <- forecast
}

```

# view output

```{r, fig.width=12, fig.height=7}
base_plot_data %>% 
  ggplot(aes(x = year)) +
  geom_line(aes(y= estimate)) +
  geom_line(aes(y =fore_CI_95_lower), linetype = "dashed") +
  geom_line(aes(y = fore_CI_95_upper), linetype = "dashed") +
  geom_point(aes(y = estimate), shape = 16) +
  geom_point(aes(y = y), shape = 21) +
  facet_grid(index~sar.method, scales = "free")+
  labs(title = "Observed vs Predicted by SAR method and Index",
       x = "Year",
       y = "Value") +
  theme_minimal() 

colors <- c("CUI" = "red", "CUTI" = "blue", "ICPB" = "green", "NCBI" = "purple")

base_plot_data %>% 
  ggplot(aes(x = year, color = index)) +
  geom_line(aes(y= estimate)) +
  geom_line(aes(y =fore_CI_95_lower), linetype = "dashed") +
  geom_line(aes(y = fore_CI_95_upper), linetype = "dashed") +
  geom_point(aes(y = estimate ), shape = 16) +
  geom_point(aes(y = y), color = "black", shape = 21) +
  scale_color_manual(values = colors)+
  facet_grid(sar.method~., scales = "free_y")+
  labs(title = "Observed vs Predicted by Index",
       x = "Year",
       y = "Value") +
  theme_bw()

base_plot_data %>% 
  ggplot(aes(x = year)) +
  geom_line(aes(y = y, color = sar.method))+
  geom_point(aes(y = y, color = sar.method), shape = 21) +
  labs(title = "Observed SAR by method input into model",
       x = "Year",
       y = "Value") +
  theme_bw()


#observed vs predicted
base_plot_data %>% 
  ggplot(aes(y = y, x = estimate)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +
  labs(y = "Observed", x = "Predicted") +
  # xlim(0,5) +
  # ylim(0,5) +
  facet_grid(index~sar.method) + 
  theme_bw()

sar.method <-  "CJS" #"DART" #"Scheurell and Williams (2005)"
index <- "CUI"
sub.qq<-filter(base_plot_data, sar.method == !!sar.method & index == !!index)


qqnorm(sub.qq$y)
qqline(sub.qq$y)

plot(density(sub.qq.marss$y, na.rm = TRUE), 
     main = "Density Plot", 
     xlab = "Values")
curve(dnorm(x, mean(sub.qq.marss$y, na.rm = TRUE), sd(sub.qq.marss$y, na.rm = TRUE)), 
      col = "red", 
      add = TRUE)

plot(density(sub.qq.dart$y, na.rm = TRUE), 
     main = "Density Plot", 
     xlab = "Values")
curve(dnorm(x, mean(sub.qq.dart$y, na.rm = TRUE), sd(sub.qq.dart$y, na.rm = TRUE)), 
      col = "red", 
      add = TRUE)

plot(density(sub.qq.cjs$y, na.rm = TRUE), 
     main = "Density Plot", 
     xlab = "Values")
curve(dnorm(x, mean(sub.qq.cjs$y, na.rm = TRUE), sd(sub.qq.cjs$y, na.rm = TRUE)), 
      col = "red", 
      add = TRUE)

```


## save files to data in compressed .rda format for golem package usage in app
```{r save_output_files, eval=FALSE}
usethis::use_data(forecast_output, overwrite = TRUE)

```


--- 
```{r fct_MARSS_model_manual forecast, eval = FALSE}
## forecast
## get list of Kalman filter output
kf_out <- MARSSkfss(dlm)


## forecasts of regr parameters; 2xT matrix - 2 in this case represents slope and intercept (2 regression parameters)
eta <- kf_out$xtt1 #one step ahead forecast of regr parameters calc with kalman filter, represented as xtt1 in marss notation


## variance of regr parameters (slope and intercept); 1x2xT array
Phi <- kf_out$Vtt1

#Since DLM is time-varying only the last values in the training data are used to forecast the next year
# Get the last forecasted regression parameters
last_eta <- eta[, ncol(eta)]

# Get the last forecasted variance
last_Phi <- Phi[, , ncol(Phi)]

#get index value for next year and standardize
test_value<-test.data$value


#get mean and standard deviation of index used in model
mean_index <- mean(index, na.rm = TRUE)
sd_index <- sd(index, na.rm = TRUE)
test_z_value <- (test_value - mean_index) / sd_index  #standardize using the train dataset mean and standard deviation (unnecessary since each index is standardized before input)
print(paste("test_z_value",test_z_value, "and", test_value, "for combination", unique(data$index), unique(data$sar.method)))



#forecast logit.s using last predicted regression parameters and z-value for next year
forecasted_logit_s <- last_eta[1] + last_eta[2] * test_z_value


# Calculate the forecasted standard error
forecasted_se <- sqrt(last_Phi[1, 1] + 2 * last_eta[2] * last_Phi[1, 2] + last_eta[2]^2 * last_Phi[2, 2])

#forecasted_s <- exp(forecasted_logit_s) / (1 + exp(forecasted_logit_s))*100
forecasted_s_plogis <- plogis(forecasted_logit_s)*100

# Calculate the prediction interval
z_value<-qnorm(.975) ## Z-value for 95% confidence interval ~1.96 (change as needed)
lower <- forecasted_s_plogis - z_value * forecasted_se
upper <- forecasted_s_plogis + z_value * forecasted_se

#create dataframe for forecast
df_nextyear<- data.frame(
  y = NA,
  estimate = forecasted_s_plogis,
  fore_CI_95_lower = lower,
  fore_CI_95_upper = upper
)

#extract predictions for all years --currently using forecast but should be using predict--doesn't seem to work by calling MARSS::predict()--could try manually extracting and calculating predictions
forecast_df<-MARSS::forecast(dlm, h= 1, type = "ytT", interval = "confidence")


  # Check if 'logit.s' and 'value' are empty--use MARSS step-ahead forecast without a index value if it is, if not empty, use test.data index value to forecast nahead
if (is.na(test.data$logit.s) && is.na(test.data$value)) {
  # If both are empty, forecast with h=1 and keep last estimate
    df_pred_raw<- forecast_df$pred

   #wrangle for plot
  df_pred<-df_pred_raw%>%
  dplyr::mutate(dplyr::across(c(,3:9), ~stats::plogis(.) * 100)) %>%
  dplyr::select(y, estimate, "fore_CI_95_lower" = `Lo 95`,"fore_CI_95_upper" = `Hi 95`)

results<-  df_pred %>%
  dplyr::mutate(year = (min(years):max(years+1)),
               index = unique(data$index),
               sar.method = unique(data$sar.method),
               dataset = "base_forecast",
                rear_type = "Natural-origin",
                pass_type = "All") %>%
  dplyr::inner_join(dplyr::select(data, value, year), by = "year") %>% ##join index value
  dplyr::select(year, value, y, estimate, fore_CI_95_lower, fore_CI_95_upper,sar.method,index, rear_type, pass_type, dataset)

  return(results)
} else {
#remove last row (incorrect forecast for next year)
df_pred_raw<- forecast_df$pred  %>% head(-1)


#wrangle for plot
df_pred<-df_pred_raw%>%
  dplyr::mutate(dplyr::across(c(,3:9), ~stats::plogis(.) * 100)) %>%
  dplyr::select(y, estimate, "fore_CI_95_lower" = `Lo 95`,"fore_CI_95_upper" = `Hi 95`)

results<-  df_pred %>%
  dplyr::bind_rows(df_nextyear) %>%
  dplyr::mutate(year = (min(years):max(years+1)),
               index = unique(data$index),
               sar.method = unique(data$sar.method),
               dataset = "base_forecast",
                rear_type = "Natural-origin",
                pass_type = "All") %>%
  dplyr::inner_join(dplyr::select(data, value, year), by = "year") %>% ##join index value
  dplyr::select(year, value, y, estimate, fore_CI_95_lower, fore_CI_95_upper,sar.method,index, rear_type, pass_type, dataset)


return(results)
}
```


